In [1]:
import pandas as pd

In [9]:
df = pd.read_csv("./data/french-ambs.csv")
df.head()

   id                name    place  year    lat   long      lat_long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57

In [16]:
df.shape

print("Number of Rows:", df.shape[0])

Number of Rows: 869

In [20]:
filtered_ambs = df.loc[(df["year"] > 1588) & (df["year"] < 1592)]

print(filtered_ambs.shape[0])
print(filtered_ambs["name"].nunique())

21
11

In [33]:
df["is_permenant"] = True
df.loc[df["place"].isin(["Geneva", "Saxony", "Tuscany", "Ferrara"]), "is_permenant"] = False
len(df.loc[df["is_permenant"] == False])

9

In [32]:
df["place"] = df["place"].replace({"Geneva": "Swiss Cantons", "Grisons": "Swiss Cantons"})
len(df.loc[df["place"] == "Swiss Cantons"])

210

In [28]:
df_agg = df.groupby("place").agg(
    years_present = ("place", "count"),
    unique_ambs = ("name", "nunique")
).sort_values("unique_ambs", ascending=True).reset_index()

df_agg

                place  years_present  unique_ambs
0              Saxony              3            1
1             Tuscany              3            1
2             Denmark             40            2
3             Ferrara              3            2
4               Savoy              4            3
5            Scotland             22            4
6              Poland              7            5
7            Portugal             56            5
8               Spain             35            5
9         Netherlands             45           12
10  Holy Roman Empire             81           15
11     Ottoman Empire             89           20
12             Venice             96           20
13               Rome             82           24
14            England             93           26
15      Swiss Cantons            210           39

In [29]:
df_agg.iloc[3]["unique_ambs"]

np.int64(2)